"""change rooms

Revision ID: 125d2f7c53ef
Revises: 6175ea0f22c4
Create Date: 2023-11-14 19:40:07.633078

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "125d2f7c53ef"
down_revision: Union[str, None] = "6175ea0f22c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "image_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "image_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
