version: "3.9"

services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB "]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    restart: always

  app:
    build: .
    env_file:
      - .env-non-dev
    depends_on:
     db:
       condition: service_healthy
     redis:
       condition: service_started
    command: [ "/booking/docker/app.sh" ]
    ports:
      - "8000:8000"

  celery:
    build: .
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env-non-dev
    command: [ "/booking/docker/celery.sh","celery" ]

  flower:
    build: .
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env-non-dev
    command: [ "/booking/docker/celery.sh","flower" ]